cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"


urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('shopping-cart/', shopping_cart, name='shopping-cart'),
]

lamancha/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
#<<<<<<< HEAD
#<<<<<<< HEAD
from django.views.generic import TemplateView

#=======
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#>>>>>>> e6e87b8146e5ce9a8545a0b4a75f7ecaf9a7ded9
#=======


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#>>>>>>> edc248909ecce69899ad1ce2ef4fb3622d4f5eb0
from lamancha.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        route='',
        view=IndexView.as_view(),
        name='index'
    ),
    path(
        route='search_book/',
        view=SearchView.as_view(),
        name='search_book'
    ),
    path(
        route='social/',
        view=Mensajeria.as_view(),
        name='red_social'
    ),

    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),


    # reset password group
    path(
        route='reset_password/',
        view=auth_views.PasswordResetView.as_view(template_name='users/auth/reset_password.html',
                                                  html_email_template_name='users/auth/send_email.html'),
        name="password_reset"),
    path(
        route='reset_password_sent/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='users/auth/reset_password_done.html'),
        name="password_reset_done"
    ),
    path(route='reset/<uidb64>/<token>/',
         view=auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"
         ),
    path(
        route='reset_password_complete/',
        view=auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # linea nueva para statics
urlpatterns += staticfiles_urlpatterns()

cart/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from cart.cart import Cart
from books.models import *


# class ShoppingCartView(TemplateView):
#     template_name = 'shopping-cart.html'
#
#     def post(self, request, *args, **kwargs):
#         cart = Cart(request)
#
#
#         # username = request.user.id
#         # book = Book.objects.get(id=bookId)
#         # order, created = Order.objects.get_or_create(user=id, complete=False)
#
#         data = {}
#         data['cart'] = cart
#         # try:
#         #     action = request.POST['action']
#         #     if action == 'searchdata':
#         #         data = []
#         #         for dc in request.user.debitCards.all():
#         #             data.append(dc.toJSON())
#         #     elif action == 'add':
#         #         data['ok'] = 'Libro añadido'
#         # except Exception as e:
#         #     data['error'] = str(e)
#         # return JsonResponse(data, safe=False)
#         return JsonResponse(data, safe=False)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # context['title'] = 'Métodos de pago'
#         # context['list_url'] = reverse_lazy('erp:client')
#         # context['entity'] = 'User'
#         context['cart'] = 'cart'
#         return context


@login_required(login_url='/users/auth/login/')
def add_product(request, product_id):
    cart = Cart(request)
    product = Book.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("cart:shopping-cart")


@login_required(login_url='/users/auth/login/')
def remove_product(request, product_id):
    cart = Cart(request)
    product = Book.objects.get(id=product_id)
    cart.remove(product)
    return redirect("cart:shopping-cart")


@login_required(login_url='/users/auth/login/')
def decrement_product(request, product_id):
    cart = Cart(request)
    product = Book.objects.get(id=product_id)
    cart.decrement(product=product)
    return redirect("cart:shopping-cart")


@login_required(login_url='/users/auth/login/')
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart:shopping-cart")


@login_required(login_url='/users/auth/login/')
def shopping_cart(request):
    cart = Cart(request)
    products = Book.objects.all()
    return render(request, "shopping-cart.html", {
        "products": products
    })

cart/templates/shopping-cart.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tags %}
{% block content %}
    <body>
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">
            <div class="row">
                <main class="col-md-9">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">
                                <i class="fas fa-shopping-cart"></i>
                                Carrito de compras</h5>
                        </div>
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Producto</th>
                                <th scope="col" width="120">Cantidad</th>
                                <th scope="col" width="120">Precio</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if request.session.cart.items %}
                                {% for key, value in request.session.cart.items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="{{ value.image }}" class="img-sm">
                                                </div>
                                                <figcaption class="info">
                                                    <a href='/books/book/details/{{ value.product_id }}' class="title text-dark">{{ value.name }}</a>
                                                    <p class="text-muted small">
                                                        Autor: {{ value.author }}<br>Editorial: {{ value.editorial }}<br>Condición: {{ value.condition }}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <div class="form-group col-md flex-grow-0">
                                                <div class="input-group mb-3 input-spinner">
                                                    <div class="input-group-prepend">
                                                        <a href="{% url 'cart:decrement_product' value.product_id %}"
                                                           class="btn btn-outline-secondary" type="button"
                                                           id="button-minus"> -
                                                        </a>
                                                    </div>
                                                    <input type="text" class="form-control" readonly="readonly"
                                                           value="{{ value.quantity }}">
                                                    <div class="input-group-append">
                                                        <a href="{% url 'cart:add_product' value.product_id %}"
                                                           class="btn btn-outline-secondary" type="button"
                                                           id="button-plus">
                                                            +
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">{{ value.price|multiply:value.quantity|money_format:"$" }}</var>
                                                <small class="text-muted"> {{ value.price }} c/u </small>
                                            </div>
                                        </td>
                                        <td class="text-right">
                                            <a href="" class="btn btn-light"> Eliminar </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4">
                                        <div class="alert alert-danger text-center">
                                            No tienes productos en el carrito
                                        </div>
                                    </td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>

                        <div class="card-body border-top">
                            <a href="#" class="btn btn-primary float-md-right"> Pagar </a>
                            <a href="{% url 'index' %}" class="btn btn-outline-secondary">
                                <i class="fa fa-chevron-left"></i> Seguir comprando </a>
                        </div>
                    </div> <!-- card.// -->

                </main> <!-- col.// -->
                <aside class="col-md-3">
                    <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                                <dt>Sub total:</dt>
                                <dd class="text-right">{{ cart_total_amount|money_format:"$" }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Descuento:</dt>
                                <dd class="text-right">0 $</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Total:</dt>
                                <dd class="text-right  h5"><strong>{{ cart_total_amount|money_format:"$" }}</strong>
                                </dd>
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                <img src="{% static 'images/misc/payments.png' %}" height="26">
                            </p>

                        </div> <!-- card-body.// -->
                    </div>  <!-- card .// -->
                </aside> <!-- col.// -->
            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

    <!-- ========================= SECTION  ========================= -->
    <section class="section-name border-top padding-y">
        <div class="container">
            <h6>Políticas de pago y reembolso</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

        </div><!-- container // -->
    </section>
    <!-- ========================= SECTION  END// ========================= -->
    </body>
{% endblock %}