cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"


urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('shopping-cart/', shopping_cart, name='shopping-cart'),
]

lamancha/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
#<<<<<<< HEAD
#<<<<<<< HEAD
from django.views.generic import TemplateView

#=======
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#>>>>>>> e6e87b8146e5ce9a8545a0b4a75f7ecaf9a7ded9
#=======


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#>>>>>>> edc248909ecce69899ad1ce2ef4fb3622d4f5eb0
from lamancha.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        route='',
        view=IndexView.as_view(),
        name='index'
    ),
    path(
        route='search_book/',
        view=SearchView.as_view(),
        name='search_book'
    ),
    path(
        route='social/',
        view=Mensajeria.as_view(),
        name='red_social'
    ),

    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),


    # reset password group
    path(
        route='reset_password/',
        view=auth_views.PasswordResetView.as_view(template_name='users/auth/reset_password.html',
                                                  html_email_template_name='users/auth/send_email.html'),
        name="password_reset"),
    path(
        route='reset_password_sent/',
        view=auth_views.PasswordResetDoneView.as_view(template_name='users/auth/reset_password_done.html'),
        name="password_reset_done"
    ),
    path(route='reset/<uidb64>/<token>/',
         view=auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"
         ),
    path(
        route='reset_password_complete/',
        view=auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # linea nueva para statics
urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>

    <title>La Mancha</title>

    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">
    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css"/>
    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Js Algorisoft -->
    <script src="{% static 'js/functions.js' %}"></script>
    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

    {% block head %}

    {% endblock %}

</head>
<body>
{% include 'header.html' %}
{% block content %}
{% endblock %}
<script>
    var items = 0
    {% if request.session.cart.items %}
        {% for key, value in request.session.cart.items %}
            items = items + {{ value.quantity }}
        {% endfor %}
    {% endif %}
    console.log(items)
    document.getElementById("cartItems").innerHTML = items;
</script>

<script>
    function formatRepo(repo) {
        if (repo.loading) {
            return repo.text;
        }

        var option = $(
            '<figure class="icontext shadow p-3">' + // revisar el shadow p-3 es para poner sombra
            '<div class="icon">' +
            '<img class="rounded img-sm border" src="' + repo.image + '">' +
            '</div>' +
            '<div class="text">' +
            '<b >Nombre:</b> ' + repo.name + '<br>' +
            '<b>Autor:</b> ' + repo.author + '<br>' +
            '<b>Precio:</b> <span class="badge badge-warning">$' + repo.price + '</span>' +
            '</div>' +
            '</figure>');

        return option;
    }

    var select_books = $('select[name="search"]');
    $(function () {
        $('.select2').select2({
            theme: "bootstrap4",
            language: 'es'
        });

        $('select[name="search"]').select2({
            theme: "bootstrap4",
            language: 'es',
            allowClear: true,
            ajax: {
                delay: 250,
                type: 'GET',
                url: '/search_book',
                data: function (params) {
                    var queryParameters = {
                        term: params.term,
                        action: 'autocomplete'
                    }
                    return queryParameters;
                },
                processResults: function (data) {
                    return {
                        results: data
                    };
                },
            },
            placeholder: 'Buscar por: autor, nombre del libro, editorial, etc',
            minimumInputLength: 1,
            templateResult: formatRepo,
        }).on('select2:select', function (e) {
            var data = e.params.data;
            console.log(data);// aquí va el código del que hacer
            location.href = "/books/book/details/" + data.id;
            //$(this).val('').trigger('change.select2'); // limpia el buscador
        });
    });
</script>

{% block javascript %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}


<footer class="section-footer bg-secondary">
    <div class="container">
        <section class="footer-bottom text-center">
            <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
            <p class="text-muted"> &copy 2020 La Mancha, All rights reserved </p>
            <br>
        </section>
    </div>
</footer>

templates/header.html
{% load static %}
<header class="section-header">
    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-2 col-lg-3 col-md-12">
                    <a href="{% url 'index' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-xl-6 col-lg-5 col-md-6">
                    <form method="GET">
                        <div class="input-group w-100">
                            <select class="select2 form-control" name="search"></select>
                            <div class="input-group-append"><a class="widget-header btn btn-outline-primary">
                                <i class="icon fas fa-search"></i></a></div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div><!-- col.// -->

                <!--  SECCIÓN DE ICONOS   -->
                {% if not request.user.is_authenticated %}
                    <!--- ICONOS PARA USUARIOS NO REGISTRADOS -->
                    <div class="col-md-5 col-lg-4 col-sm-12 col-12 text-md-right">
                        <div class="mt-3 mt-md-0">
                            <a href="{% url 'login' %}" class="btn btn-outline-primary"><i
                                    class="fas fa-sign-in-alt"></i> Ingresar </a>
                            <a href="{% url 'signup' %}" class="btn btn-primary"> Registrarse </a>
                            <a href="#" class="widget-header mr-2">
                                <i class="text-primary icon icon-sm rounded-circle border fa fa-shopping-cart"></i>
                                <span class="notify">2</span></a>
                        </div>
                    </div>
                {% else %} <!---- ICONOS PARA USUARIOS REGISTRADOS -->
                    <div class="col-md-5 col-lg-4 col-sm-12 col-12 text-md-right">
                        <div class="mt-3 mt-md-0">
                            <a href="{% url 'profile' request.user.id %}" class="widget-header mr-2"><i
                                    class="text-primary icon icon-sm rounded-circle border fa fa-user"></i></a>
                            <!-- aquí se deben ir al la configuración -->
                            <a href="#" class="widget-header mr-2"><i
                                    class="text-primary icon icon-sm rounded-circle border fa fa-inbox"></i>
                                <span class="notify">2</span></a>
                            <!-- aquí se deben mostar los mensajes que tenga el usuario -->
                            {% if not user.is_staff %}
                                <a href="{% url 'cart:shopping-cart' %}" class="widget-header mr-2">
                                    <i class="text-primary icon icon-sm rounded-circle border fa fa-shopping-cart"></i>
                                    <span id="cartItems" class="notify">0</span></a>
                            {% endif %}
                            <!-- aquí se deben mostrar los elementos en el carrito -->
                            <a href="{% url 'logout' %}" class="widget-header mr-2"><i
                                    class="text-primary icon icon-sm rounded-circle border fa fa-sign-out-alt"></i></a>
                            <!-- cerrar sesión -->
                        </div>
                    </div>
                {% endif %}
            </div> <!-- container.// -->
    </section> <!-- header-main .// -->
</header> <!-- section-header.// -->

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
    <b class="screen-overlay"></b>
    <div class="container">
        <!-- ========================= SECTION MAIN  ========================= -->
        <section class="section-main padding-y">
            <main class="card">
                <div class="card-body">
                    <div class="row">
                        <aside class="col-lg col-md-3 flex-lg-grow-0">
                            <nav class="nav-home-aside">
                                <h6 class="title-category">CATEGORÍAS <i class="d-md-none icon fa fa-chevron-down"></i>
                                </h6>
                                <ul class="menu-category">
                                    <li><a href="#">Romance</a></li>
                                    <li><a href="#">Ficción</a></li>
                                    <li><a href="#">Drama</a></li>
                                    <li><a href="#">Cinetífico</a></li>
                                    <li><a href="#">Policial</a></li>
                                    <li><a href="#">Infantil</a></li>
                                    <li><a href="#">Noveles</a></li>
                                    <li class="has-submenu"><a href="#">Más géneros</a>
                                        <ul class="submenu">
                                            <li><a href="#">Ánime</a></li>
                                            <li><a href="#">Manga</a></li>
                                            <li><a href="#">Educación sexual</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </aside> <!-- col.// -->
                        <div class="col-md-9 col-xl-7 col-lg-7">

                            <!-- ================== COMPONENT SLIDER  BOOTSTRAP  ==================  -->
                            <div id="carousel1_indicator" class="slider-home-banner carousel slide"
                                 data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel1_indicator" data-slide-to="1"></li>
                                    <li data-target="#carousel1_indicator" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="{% static 'images/banners/hobbit.jpg' %}" alt="First slide">
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'images/banners/harry potter.jpg' %}" alt="Second slide">
                                    </div>
                                    <div class="carousel-item">
                                        <img src="{% static 'images/banners/50 sombras.jpg' %}" alt="Third slide">
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carousel1_indicator" role="button"
                                   data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel1_indicator" role="button"
                                   data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            <!-- ==================  COMPONENT SLIDER BOOTSTRAP end.// ==================  .// -->

                        </div> <!-- col.// -->
                        <div class="col-md d-none d-lg-block flex-grow-1">
                            <aside class="special-home-right">
                                <h6 class="bg-blue text-center text-white mb-0 p-2">Más vendidos</h6>

                                <!-- MAS VENDIDOS -->
                                {% for book in  books %}
                                    <div class="card-banner border-bottom">
                                        <div class="py-3" style="width:80%">
                                            <h6 class="card-title">{{ book.title }}</h6>
                                            <a href='books/book/details/{{ book.pk }}' class="btn btn-secondary btn-sm">Ver
                                                ahora</a>
                                        </div>
                                        <img src="{{ book.get_image }}" height="80" class="img-bg">
                                    </div>
                                {% endfor %}

                            </aside>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->

                </div> <!-- card-body.// -->
            </main> <!-- card.// -->

        </section>
        <!-- ========================= SECTION MAIN END// ========================= -->
        <!-- =============== SECTION ITEMS =============== -->
        <section class="padding-bottom-sm">
            <header class="section-heading heading-line">
                <h4 class="title-section text-uppercase"> Recomendados para ti </h4>
            </header>
            <div class="row row-sm">
                <!-- RECOMENDADOS PARA TI -->
                {% for book in books %}
                    <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                        <div class="card card-sx card-product-grid">
                            <figcaption class="info-wrap">
                                <a href='books/book/details/{{ book.pk }}' class="img-wrap"> <img
                                        src="{{ book.get_image }}">
                                </a>
                                <a href='books/book/details/{{ book.pk }}'
                                   class="text-center title">{{ book.title }}</a>
                                <div class="text-center price mt-1">{{ book.price }}</div>
                            </figcaption>
                        </div>
                    </div> <!-- col.// -->
                {% endfor %}
            </div> <!-- row.// -->
        </section>
    </div>
        <!-- =============== SECTION ITEMS .//END =============== -->
    </body>
{% endblock %}
{% block javascript %}

{% endblock %}

templates/mensajes.html
<!DOCTYPE html>
<html>
<head>
	<title>Prueba mensajes</title>
</head>
<body>
<!-- Construct the box with style you want. Here we are using box-danger -->
<!-- Then add the class direct-chat and choose the direct-chat-* contexual class -->
<!-- The contextual class should match the box, so we are using direct-chat-danger -->
<div class="box box-danger direct-chat direct-chat-danger">
  <div class="box-header with-border">
    <h3 class="box-title">Direct Chat</h3>
    <div class="box-tools pull-right">
      <span data-toggle="tooltip" title="3 New Messages" class="badge bg-red">3</span>
      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      <!-- In box-tools add this button if you intend to use the contacts pane -->
      <button class="btn btn-box-tool" data-toggle="tooltip" title="Contacts" data-widget="chat-pane-toggle"><i class="fa fa-comments"></i></button>
      <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <!-- Conversations are loaded here -->
    <div class="direct-chat-messages">
      <!-- Message. Default to the left -->
      <div class="direct-chat-msg">
        <div class="direct-chat-info clearfix">
          <span class="direct-chat-name pull-left">Alexander Pierce</span>
          <span class="direct-chat-timestamp pull-right">23 Jan 2:00 pm</span>
        </div>
        <!-- /.direct-chat-info -->
        <img class="direct-chat-img" src="../dist/img/user1-128x128.jpg" alt="message user image">
        <!-- /.direct-chat-img -->
        <div class="direct-chat-text">
          Is this template really for free? That's unbelievable!
        </div>
        <!-- /.direct-chat-text -->
      </div>
      <!-- /.direct-chat-msg -->

      <!-- Message to the right -->
      <div class="direct-chat-msg right">
        <div class="direct-chat-info clearfix">
          <span class="direct-chat-name pull-right">Sarah Bullock</span>
          <span class="direct-chat-timestamp pull-left">23 Jan 2:05 pm</span>
        </div>
        <!-- /.direct-chat-info -->
        <img class="direct-chat-img" src="../dist/img/user3-128x128.jpg" alt="message user image">
        <!-- /.direct-chat-img -->
        <div class="direct-chat-text">
          You better believe it!
        </div>
        <!-- /.direct-chat-text -->
      </div>
      <!-- /.direct-chat-msg -->
    </div>
    <!--/.direct-chat-messages-->

    <!-- Contacts are loaded here -->
    <div class="direct-chat-contacts">
      <ul class="contacts-list">
        <li>
          <a href="#">
            <img class="contacts-list-img" src="../dist/img/user1-128x128.jpg" alt="Contact Avatar">
            <div class="contacts-list-info">
              <span class="contacts-list-name">
                Count Dracula
                <small class="contacts-list-date pull-right">2/28/2015</small>
                </span>
              <span class="contacts-list-msg">How have you been? I was...</span>
            </div>
            <!-- /.contacts-list-info -->
          </a>
        </li>
        <!-- End Contact Item -->
      </ul>
      <!-- /.contatcts-list -->
    </div>
    <!-- /.direct-chat-pane -->
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <div class="input-group">
      <input type="text" name="message" placeholder="Type Message ..." class="form-control">
      <span class="input-group-btn">
                <button type="button" class="btn btn-danger btn-flat">Send</button>
                </span>
    </div>
  </div>
  <!-- /.box-footer-->
</div>
<!--/.direct-chat -->
</body>
</html>

templates/simple_base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Bootstrap e-commerce html template similar to Alibaba">
    <meta name="keywords" content="Online template, shop, theme, template, html, css, bootstrap 4">

    <title>La Mancha</title>

    <link href="{% static 'images/favicon.ico'%}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js'%}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css'%}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css'%}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="{% static 'js/script.js'%}" type="text/javascript"></script>

    <!-- Sweetalert2 -->
    <script src="{% static 'sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>

    <!-- js algoritsof register -->
        <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>

    {% block head %}
    {% endblock %}

</head>
<body>
{% block content %}

{% endblock %}
{% include 'footer.html' %}
</body>
</html>